### ISSUE TITLE
CentOS and Ubuntu などのSSHでは出力系は正常に動作しない

### ISSUE THREAD

**Issue by kamata4649** [JupiterDevelopmentTeam/Jupiter#49]
## エラー内容

banner.pngがない場合

```
21:11:50 [INFO] リソースパックを読み込みました
> サーバーを停止しています...
21:11:52 [INFO] スレッドが停止しました。
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: 0
        at java.lang.AbstractStringBuilder.charAt(AbstractStringBuilder.java:237)
        at java.lang.StringBuilder.charAt(StringBuilder.java:76)
        at jline.console.ConsoleReader.wcwidth(ConsoleReader.java:555)
        at jline.console.ConsoleReader.backspace(ConsoleReader.java:1057)
        at jline.console.ConsoleReader.backspaceAll(ConsoleReader.java:1043)
        at jline.console.ConsoleReader.resetPromptLine(ConsoleReader.java:3858)
        at cn.nukkit.command.CommandReader.removePromptLine(CommandReader.java:125)
        at cn.nukkit.Nukkit.main(Nukkit.java:120)
> >
Took too long to stop, server was killed forcefully!

21:12:00 [NOTICE] Trayに対応していないOSの為、表示しませんでした。(エラーではありません)
```

banner.pngがある場合

```
21:17:10 [INFO] スレッドが停止しました。
サーバーが停止しました。
21:17:10 [EMERGENCY] RakNet(サーバー)がクラッシュしました。
> Exception in thread "Thread-5" java.lang.IllegalStateException: Shutdown in progress
        at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
        at java.lang.Runtime.addShutdownHook(Runtime.java:211)
        at com.sun.imageio.stream.StreamCloser$2.run(StreamCloser.java:101)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.imageio.stream.StreamCloser.addToQueue(StreamCloser.java:84)
        at javax.imageio.stream.FileCacheImageInputStream.<init>(FileCacheImageInputStream.java:109)
        at com.sun.imageio.spi.InputStreamImageInputStreamSpi.createInputStreamInstance(InputStreamImageInputStreamSpi.java:69)
        at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357)
        at javax.imageio.ImageIO.read(ImageIO.java:1351)
        at cn.nukkit.Server.getTrayIcon(Server.java:693)
        at cn.nukkit.Server.trayMessage(Server.java:711)
        at cn.nukkit.Server.trayMessage(Server.java:707)
        at cn.nukkit.raknet.server.RakNetServer$ShutdownHandler.run(RakNetServer.java:92)
```

改善方法として、Out系(画像出力をなくすと改善されると考えています)

**Comment by itsu020402** [comment]
Jupiterのご使用並びにご報告ありがとうございます。
将来的にはGUI関連の装飾はJupiter.ymlでオン/オフを切り替えられるようにする予定です。
対応までもう少しお待ちください。

**Comment by itsu020402** [comment]
Jupiter.ymlにてguiモードの使用を許可しない設定を加えることによって対応しました。

なお、スプラッシュ画面は許可の可否にかかわらず表示しないようにしました。
