### ISSUE TITLE
初回起動時にエラー（起動に問題はなし）

### ISSUE THREAD

**Issue by popkechupki** [JupiterDevelopmentTeam/Jupiter#52]
nukkit-1.0-SNAPSHOT.jarを実行すると
` [ALERT] java.lang.NullPointerException
        at cn.nukkit.utils.MainLogger.flushBuffer(MainLogger.java:246)
        at cn.nukkit.utils.MainLogger.run(MainLogger.java:219)`
と表示される。言語選択はそのエラーの後に通常通り表示される。

**Comment by Megapix96** [comment]
私の環境では再現出来ませんでした...
start.batとnukkit-1.0-SNAPSHOT.jarのみで起動しました。

**Comment by itsu020402** [comment]
同じく発生しませんでした。
