### ISSUE TITLE
Raknet crash on starting the server

### ISSUE THREAD

**Issue by GeoZDev** [JupiterDevelopmentTeam/Jupiter#80]
07:29:02 [INFO]
07:29:02 [INFO] Jupiter by JupiterDevelopmentTeam
07:29:02 [INFO]
07:29:02 [INFO]
07:29:02 [INFO] nukkit.yml?????????...
07:29:02 [INFO] server.properties?????????...
07:29:02 [INFO] jupiter.yml?????????...
07:29:02 [INFO] Selected English (eng) as the base language
07:29:02 [INFO] Starting Minecraft: PE server version v1.2.7
07:29:02 [INFO] Opening server on 0.0.0.0:19135
07:29:02 [INFO] Jupiter is distributed under the LGPL License
07:29:03 [INFO] Loading recipes...
07:29:03 [INFO] Loaded 415 recipes.
07:29:03 [INFO] ???????????????
> ????????????...
????????????
07:29:03 [INFO] ????????????
07:29:03 [EMERGENCY] RakNet(????)???????????
> Exception in thread "Thread-5" java.lang.IllegalStateException: Shutdown in progress
        at java.lang.ApplicationShutdownHooks.add(ApplicationShutdownHooks.java:66)
        at java.lang.Runtime.addShutdownHook(Runtime.java:211)
        at com.sun.imageio.stream.StreamCloser$2.run(StreamCloser.java:101)
        at java.security.AccessController.doPrivileged(Native Method)
        at com.sun.imageio.stream.StreamCloser.addToQueue(StreamCloser.java:84)
        at javax.imageio.stream.FileCacheImageInputStream.<init>(FileCacheImageInputStream.java:109)
        at com.sun.imageio.spi.InputStreamImageInputStreamSpi.createInputStreamInstance(InputStreamImageInputStreamSpi.java:69)
        at javax.imageio.ImageIO.createImageInputStream(ImageIO.java:357)
        at javax.imageio.ImageIO.read(ImageIO.java:1351)
        at cn.nukkit.Server.getTrayIcon(Server.java:725)
        at cn.nukkit.Server.trayMessage(Server.java:740)
        at cn.nukkit.raknet.server.RakNetServer$ShutdownHandler.run(RakNetServer.java:92)

**Comment by itsu020402** [comment]
Thank you for using Jupiter,

If you downloaded Jupiter from official site, it is very old one.
So you can use https://github.com/itsu020402/Temp/blob/master/nukkit-1.0-SNAPSHOT.jar .
Maybe this Jupiter was fixed the bug.
